### PR TITLE
Fix bug in Blink.msg

### LINKED ISSUE #65: Method error when a getindex(::Int64, ::ASCIIString) is called as a result of a simple UI
If I build a simple UI with Blink:

``` julia
using Blink
w = Window()
body!(w, "My Fancy App!<br/><br/><button id='gobutton'>Click me!</button>")
handle(w, "press") do args...
         println("Hello world!")
end
@js_ w document.getElementById("gobutton").onclick = () -> Blink.msg("press", "foo")
```

Results in a method error when the button in the UI is clicked. 

```
MethodError: `getindex` has no method matching getindex(::Int64, ::ASCIIString)
Closest candidates are:
  getindex(::Number)
  getindex(::Number, ::Integer)
  getindex(::Number, ::Integer...)
  ...
 [inlined code] from /Users/axolotlfan9250/.julia/v0.4/Lazy/src/macros.jl:259
 in ws_handler at /Users/axolotlfan9250/.julia/v0.4/Blink/src/content/server.jl:53
 in splitquery at /Users/axolotlfan9250/.julia/v0.4/Mux/src/basics.jl:28
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/Mux.jl:8
 in wcatch at /Users/axolotlfan9250/.julia/v0.4/Mux/src/websockets_integration.jl:12
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/Mux.jl:8
 in todict at /Users/axolotlfan9250/.julia/v0.4/Mux/src/basics.jl:21
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/Mux.jl:12 (repeats 2 times)
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/Mux.jl:8
 in anonymous at /Users/axolotlfan9250/.julia/v0.4/Mux/src/server.jl:38
 in handle at /Users/axolotlfan9250/.julia/v0.4/WebSockets/src/WebSockets.jl:382
 in on_message_complete at /Users/axolotlfan9250/.julia/v0.4/HttpServer/src/HttpServer.jl:419
 in on_message_complete at /Users/axolotlfan9250/.julia/v0.4/HttpServer/src/RequestParser.jl:104
 in http_parser_execute at /Users/axolotlfan9250/.julia/v0.4/HttpParser/src/HttpParser.jl:92
 in process_client at /Users/axolotlfan9250/.julia/v0.4/HttpServer/src/HttpServer.jl:388
 in anonymous at task.jl:447
```

### PR DESCRIPTION
**Pull request by shashi**
`m.type = t` would succeed when `m` is a `String`, however JSON.stringify serializes `m` as a string losing the type field.

This PR requires "type" and "data" field in every message

fixes #65

### CODE REVIEW

File: res/blink.js [hunk 1]
```diff
@@ -11,12 +11,10 @@
...
   function msg(t, m) {
-    if (m === undefined) {
-      m = t;
-    } else {
-      m.type = t;
-    }
-    sock.send(JSON.stringify(m));
+    sock.send(JSON.stringify({
+      type: m === undefined ? t.type : t,
+      data: m
```
Comment (MikeInnes) [inline res/blink.js]: I think the idea of this was to support both `msg('foo', {bar: 'baz'})` and `msg({type: 'foo', bar: 'baz'})`; this would behave differently in the second case. If we make this change we should probably just get rid of that altogether.

Comment (shashi) [inline res/blink.js]: Second case results in a message `{type: 'foo', data: { type: 'foo', bar: 'baz'}}` and the handler is called with `msg["data"]` on Julia - which is the same as it used to be. So this change is backwards compatible.

**Comment by MikeInnes** [comment]
Thanks!
