### PR TITLE
Always call `evalscripts` in `fill`.

### LINKED ISSUE #109: `content!` incorrectly skips `evalscripts` if `fade=false`
`content!` incorrectly skips `evalscripts` if `fade=false`.

If it's true, it uses the javascript `Blink.fill` function, which sets the innerHTML and calls `evalscripts()`:
https://github.com/JunoLab/Blink.jl/blob/e25741d0634f5ab9c6f5052e829eb88d4b6837f6/res/blink.js#L106-L107

Otherwise it manually fills the html, and forgets to call `evalscripts()`:
https://github.com/JunoLab/Blink.jl/blob/e25741d0634f5ab9c6f5052e829eb88d4b6837f6/src/content/api.jl#L3-L6

### PR DESCRIPTION
**Pull request by NHDaly**
Fixes #109.

Moves the fade/no-fade decision from Julia down into javascript, so that
more code can be reused whether or not `fade == true`.

This also simplifies the `content!` function body, which will make
fixing #108 a bit easier.

### CODE REVIEW

**Comment by NHDaly** [comment]
(per suggestions on slack, I'm happy to move the tests into their own test specific to `api.jl`!)

File: src/content/api.jl [hunk 1]
```diff
@@ -1,9 +1,7 @@
 export body!, content!, loadcss!, loadjs!, load!, importhtml!
 
 content!(o, sel, html::AbstractString; fade = true) =
-  fade ?
-    @js_(o, Blink.fill($sel, $html)) :
-    @js_ o document.querySelector($sel).innerHTML = $html
+    @js_(o, Blink.fill($sel, $html, $(fade ? 1 : 0)))
```
Comment (pfitzseb) [inline src/content/api.jl]: Is the `fade ? 1 : 0` really necessary?

File: test/runtests.jl [hunk 2]
```diff
@@ -13,4 +13,37 @@ w = Window(Blink.@d(:show => false)); sleep(5.0)
 
 @test sprint(Blink.jsexpr, :(Dict("a" => 1, :b => 10))) == "{\"a\":1,b:10}"
 
+@testset "content! Tests" begin
```
Comment (pfitzseb) [inline test/runtests.jl]: Moving this testset to `test/api.jl` would be great :)

Comment (NHDaly) [reply test/runtests.jl]: Oops! Thanks. I started rebasing this, but never finished it looks like.. Let me push that up now!

File: src/content/api.jl (hunk 1 above)
Comment (NHDaly) [reply src/content/api.jl]: Oops, no, it's definitely not. Thanks. I think I was worried that javascript doesn't have values for `true` or `false`, but that's silly. XD
Fixed in the rebased version i just pushed! :) thanks!

**Comment by NHDaly** [comment]
Thanks!
